### ISSUE TITLE
Should the team score page be public?

### ISSUE THREAD

**Issue by jviide** [ouspg/urlhandlers-assembly-app#7]
Should the team score page be public, should we limit the access to it through auth?

**Comment by jviide** [comment]
Ping @nkapu, @execgit & @ikisusi.

**Comment by execgit** [comment]
No objections on scores being public - on the other hand, I wouldn't require it either. Due to timing constraints, auth would probably be a safer bet.

**Comment by ikisusi** [comment]
Public 👍

**Comment by jviide** [comment]
Roger that, public it is. Closing this issue.
